
export default sleepy = [
    {
        id: 1,
        name: 'Rain on Window',
        type: 'rain',
        blur: require('../assets/images/sleepy/blur/rainonwindowblur.png'),
        image: require('../assets/images/sleepy/normal/rainonwindow.png'),
        sound: require('../assets/sounds/rainonwindow.mp3'),
    },
    {
        id: 2,
        name: 'Rain in Forest',
        type: 'rain',
        blur: require('../assets/images/sleepy/blur/raininforestblur.png'),
        image: require('../assets/images/sleepy/normal/raininforest.png'),
        sound: require('../assets/sounds/raininforest.mp3'),
    },
    {
        id: 3,
        name: 'Refeshing Rain',
        type: 'rain',
        blur: require('../assets/images/sleepy/blur/raininforestblur.png'),
        image: require('../assets/images/sleepy/normal/refeshingrain.png'),
        sound: require('../assets/sounds/refreshingrain.mp3'),
    },
    {
        id: 4,
        name: 'Thunderstorm',
        type: 'rain',
        blur: require('../assets/images/sleepy/blur/thunderstormblur.png'),
        image: require('../assets/images/sleepy/normal/thunderstorm.png'),
        sound: require('../assets/sounds/thunderstorm.mp3'),
    },
    {
        id: 5,
        name: 'Quiet Cave',
        type: 'nature',
        blur: require('../assets/images/sleepy/blur/quietcaveblur.png'),
        image: require('../assets/images/sleepy/normal/quietcave.png'),
        sound: require('../assets/sounds/quietcave.mp3'),
    },
    {
        id: 6,
        name: 'Peaceful Night',
        type: 'nature',
        blur: require('../assets/images/sleepy/blur/peacefulnightblur.png'),
        image: require('../assets/images/sleepy/normal/peacefulnight.png'),
        sound: require('../assets/sounds/peacefulnight.mp3'),
    },
    {
        id: 7,
        name: 'Desert',
        type: 'nature',
        blur: require('../assets/images/sleepy/blur/desertblur.png'),
        image: require('../assets/images/sleepy/normal/desert.png'),
        sound: require('../assets/sounds/desert.mp3'),
    },
    {
        id: 8,
        name: 'Autumn Woods',
        type: 'nature',
        blur: require('../assets/images/sleepy/blur/autumnwoodsblur.png'),
        image: require('../assets/images/sleepy/normal/autumnwoods.png'),
        sound: require('../assets/sounds/autumnwoods.mp3'),
    },
    {
        id: 9,
        name: 'Lake',
        type: 'nature',
        blur: require('../assets/images/sleepy/blur/lakeblur.png'),
        image: require('../assets/images/sleepy/normal/lake.png'),
        sound: require('../assets/sounds/lake.mp3'),
    },
    {
        id: 10,
        name: 'Ocean',
        type: 'nature',
        blur: require('../assets/images/sleepy/blur/oceanblur.png'),
        image: require('../assets/images/sleepy/normal/ocean.png'),
        sound: require('../assets/sounds/ocean.mp3'),
    },
    {
        id: 11,
        name: 'Winter',
        type: 'nature',
        blur: require('../assets/images/sleepy/blur/winterblur.png'),
        image: require('../assets/images/sleepy/normal/winter.png'),
        sound: require('../assets/sounds/winter.mp3'),
    },
    {
        id: 12,
        name: 'Frogs',
        type: 'animals',
        blur: require('../assets/images/sleepy/blur/frogsblur.png'),
        image: require('../assets/images/sleepy/normal/frogs.png'),
        sound: require('../assets/sounds/frogs.mp3'),
    },
    {
        id: 13,
        name: 'Crickets',
        type: 'animals',
        blur: require('../assets/images/sleepy/blur/cricketsblur.png'),
        image: require('../assets/images/sleepy/normal/crickets.png'),
        sound: require('../assets/sounds/crickets.mp3'),
    },
    {
        id: 14,
        name: 'Birds',
        type: 'animals',
        blur: require('../assets/images/sleepy/blur/birdsblur.png'),
        image: require('../assets/images/sleepy/normal/birds.png'),
        sound: require('../assets/sounds/birds.mp3'),
    },
    {
        id: 15,
        name: 'Owls',
        type: 'animals',
        blur: require('../assets/images/sleepy/blur/owlsblur.png'),
        image: require('../assets/images/sleepy/normal/owls.png'),
        sound: require('../assets/sounds/owls.mp3'),
    },

    {
        id: 16,
        name: 'Wolves',
        type: 'animals',
        blur: require('../assets/images/sleepy/blur/wolvesblur.png'),
        image: require('../assets/images/sleepy/normal/wolves.png'),
        sound: require('../assets/sounds/wolves.mp3'),
    },
]