export default foods = [
    {
        id: 1,
        name: 'Strawberry',
        vnname: 'Dâu tây',
        type: 'fruit',
        image: require('../assets/images/foods/strawberry.png'),
        color: '#ffe8e8',
        nutritionalValue: {
            calories: 32,
            lipid: 0.3,
            cholesterol: 0,
            natri: 1,
            kali: 153,
            cacbohydrat: 8,
            protein: 0.7
        },
        infomations: 'Dâu tây có màu đỏ tươi, ngon ngọt và ngọt ngào.Chúng là một nguồn tuyệt vời của vitamin C và mangan và cũng chứa một lượng folate (vitamin B9) và kali. Dâu tây rất giàu chất chống oxy hóa và các hợp chất thực vật, có thể có lợi cho sức khỏe tim mạch và kiểm soát lượng đường trong máu.'
    },
    {
        id: 2,
        name: 'Carrot',
        vnname: 'Cà rốt',
        type: 'vegetables',
        image: require('../assets/images/foods/carrot.png'),
        color: '#fff1de',
        nutritionalValue: {
            calories: 41,
            lipid: 0.2,
            cholesterol: 0,
            natri: 69,
            kali: 320,
            cacbohydrat: 10,
            protein: 0.9
        },
        infomations: 'Cà rốt có khả năng điều tiết cơ năng sinh lý của cơ thể, tăng cường thể chất, tăng miễn dịch, kháng khuẩn, giải độc, làm hạ đường huyết, dự phòng tích cực các bệnh lý do thiếu vitamin A, cao huyết áp, vữa xơ động mạch, đau thắt ngực và nhồi máu cơ tim.',
        
    },
    {
        id: 3,
        name: 'Watermelon',
        vnname: 'Dưa hấu',
        type: 'fruit',
        image: require('../assets/images/foods/watermelon.png'),
        color: '#e3fff0',
        nutritionalValue: {
            calories: 30,
            lipid: 0.2,
            cholesterol: 0,
            natri: 1,
            kali: 112,
            cacbohydrat: 8,
            protein: 0.6
        },
        infomations: 'Dưa hấu là một trong những loại trái cây có lượng calo thấp (Chỉ 46 calo mỗi cốc 154 g), thấp hơn so với các loại trái cây ít đường khác. Tuy nhiên, nó lại có rất nhiều chất dinh dưỡng, bao gồm vitamin và khoáng chất. Trong 154 g dưa hấu sẽ bao gồm 21% vitamin C, 18% vitamin A, 5% kali, 4% magie và 3% các vitamin B1, B5, B6.',
    },
    {
        id: 4,
        name: 'Eggplant',
        vnname: 'Cà tím',
        type: 'fruit',
        image: require('../assets/images/foods/eggplant.png'),
        color: '#dfdeff',
        info: 'eggplant',
        nutritionalValue: {
            calories: 24,
            lipid: 0.2,
            cholesterol: 0,
            natri: 2,
            kali: 229,
            cacbohydrat: 6,
            protein: 1
        },
        infomations: 'Cà tím chứa rất ít calo, không chứa chất béo, và lượng chất xơ cao giúp tạo ra cảm giác no. Nếu bạn học cách chế biến nó thành những món ăn hấp dẫn, cà tím sẽ là người bạn tốt của những ai đang muốn ăn kiêng.',
    },
    {
        id: 5,
        name: 'Chili',
        vnname: 'Ớt',
        type: 'fruit',
        image: require('../assets/images/foods/chili.png'),
        color: '#ffe0e1',
        nutritionalValue: {
            calories: 101,
            lipid: 3.3,
            cholesterol: 53,
            natri: 398,
            kali: 273,
            cacbohydrat: 9,
            protein: 10
        },
        infomations: 'Thành phần capsaicin trong ớt có khả năng ức chế sự phát triển của các tế bào ung thư và ngăn chặn các mầm mống bệnh phát triển. Vitamin A có trong ớt rất tốt đối với sức khỏe và tuổi thọ; có lợi cho mắt, tăng cường khả năng miễn dịch và thúc đẩy tăng trưởng tế bào.',
    },
    {
        id: 6,
        name: 'Orange',
        vnname: 'Cam',
        type: 'fruit',
        image: require('../assets/images/foods/orange.png'),
        color: '#fff5e6',
        nutritionalValue: {
            calories: 47,
            lipid: 0.1,
            cholesterol: 0,
            natri: 0,
            kali: 181,
            cacbohydrat: 12,
            protein: 0.9
        },
        infomations: 'Cam là loại quả rất giàu chất dinh dưỡng. Người ta tính ra trong mỗi 100 gr quả cam có chứa 87,6 g nước, 1.104 microgram carotene, 30 mg vitamin C, 10,9 g chất tinh bột, 93 mg kali, 26 mg canxi. Ngoài ra, với trọng lượng cam tương tự còn có chứa 9 mg magnesium, 0,3 g chất xơ, 4,5 mg natri, 7 mg chromium, 20 mg phốt pho, 0,32 mg sắt và giá trị năng lượng là 48 Kcal. Cam rất giàu chất chống oxy hóa phytochemical.',
    },
    {
        id: 7,
        name: 'Apple',
        vnname: 'Táo',
        type: 'fruit',
        image: require('../assets/images/foods/apple.png'),
        color: '#ffe3e3',
        nutritionalValue: {
            calories: 52,
            lipid: 0.2,
            cholesterol: 0,
            natri: 1,
            kali: 107,
            cacbohydrat: 14,
            protein: 0.3
        },
        infomations: 'Táo là loại trái cây chứa thành phần dinh dưỡng đa dạng, bao gồm chất xơ, nguyên tố vi lượng, nước, vitamin và các chất chống oxy hóa. Hợp chất chống oxy hóa Quercetin trong táo có tác dụng ngăn chặn quá trình thoái hóa và viêm ở các tế bào thần kinh. Hàm lượng vi chất dinh dưỡng lành mạnh trong táo còn có tác dụng giảm cholesterol LDL (xấu) và tăng hàm lượng cholesterol HDL (tốt) đáng kể.',
    },
    {
        id: 8,
        name: 'Zucchini',
        vnname: 'Bí ngòi',
        type: 'vegetables',
        image: require('../assets/images/foods/zucchini.png'),
        color: '#f3ffde',
        nutritionalValue: {
            calories: 1,
            lipid: 0.3,
            cholesterol: 0,
            natri: 8,
            kali: 261,
            cacbohydrat: 3.1,
            protein: 1.2
        },
        infomations: 'Lượng chất xơ dồi dào trong bí ngòi có tác dụng ngăn ngừa các độc tố gây bệnh ung thư ruột kết cũng như tăng cường sức khỏe và bình ổn chuyển động của các nhu động ruột. Vitamin A và C của bí ngòi còn là những chất kháng oxy hóa mạnh giúp tiêu diệt các gốc tự do, ngừa những bệnh ung thư ác tính. Bí ngòi xanh có hàm lượng calo đặc biệt thấp, nhưng lại chứa rất nhiều nước.',
    },
    {
        id: 9,
        name: 'Onion',
        vnname: 'Hành tây',
        type: 'vegetables',
        image: require('../assets/images/foods/onion.png'),
        color: '#ffdbe9',
        nutritionalValue: {
            calories: 39,
            lipid: 0.1,
            cholesterol: 0,
            natri: 4,
            kali: 146,
            cacbohydrat: 9,
            protein: 1.1
        },
        infomations: 'Hành tây dùng sống hoặc nấu chín đều được dung nạp tốt và mang lại nhiều lợi ích cho sức khỏe. Hành cung cấp một nguồn vitamin C, B6, sắt, Kali và Mangan để bảo vệ cơ thể khỏi cái lạnh và cảm cúm. Do đó, bạn có thể ăn Hành tây bất cứ lúc nào bạn muốn. Các chất phytochemical, Allium và Allyl Disulphide có trong hành có đặc tính chống ung thư và chống lại tiểu đường. Hợp chất này cũng làm giảm độ cứng của mạch máu và giúp huyết áp.',
    },
    {
        id: 10,
        name: 'Potato',
        vnname: 'Khoai tây',
        type: 'vegetables',
        image: require('../assets/images/foods/potato.png'),
        color: '#d4c9c5',
        nutritionalValue: {
            calories: 76,
            lipid: 0.1,
            cholesterol: 0,
            natri: 6,
            kali: 421,
            cacbohydrat: 17,
            protein: 2
        },
        infomations: 'Khoai tây là một trong những loại thực phẩm giúp bổ sung sắt tự nhiên cho sức khỏe. Sắt có ảnh hưởng to lớn đến sự phát triển bình thường của cơ thể, tham gia sản xuất các tế bào máu, chống stress, duy trì các cơ bắp và điều chỉnh sự hoạt động của các tế bào. Củ khoai tây rất giàu magie. Khoáng chất này giúp tinh thần thư giãn và chống căng thẳng. Nó là yếu tố cần thiết, tham gia vào quá trình chuyển hóa năng lượng, tạo xương và mô, tốt cho hoạt động của hệ thần kinh.',
    },
    {
        id: 11,
        name: 'Tomato',
        vnname: 'Cà chua',
        type: 'vegetables',
        image: require('../assets/images/foods/tomato.png'),
        color: '#ffe0e1',
        nutritionalValue: {
            calories: 19,
            lipid: 0.2,
            cholesterol: 0,
            natri: 42,
            kali: 3.7,
            cacbohydrat: 3.9,
            protein: 0.9
        },
        infomations: 'Cà chua rất giàu vitamin A, C, K, vitamin B6, kali, folate, thiamin, magiê, niacin, đồng và phốt pho, là những vi chấtcần thiết để duy trì một sức khỏe tốt. Điều tuyệt vời hơn ở cà chua là chúng chứa rất ít cholesterol, chất béo bão hòa, natri và calo. Bạn có thể ăn cà chua sống kẹp với bánh mì, làm salad, nước sốt, sinh tố, thậm chí nấu súp',
    },
    {
        id: 12,
        name: 'Peanuts',
        vnname: 'Đậu phộng',
        type: 'nutsandseeds',
        image: require('../assets/images/foods/peanuts.png'),
        color: '#fff2db',
        nutritionalValue: {
            calories: 567,
            lipid: 49,
            cholesterol: 0,
            natri: 18,
            kali: 705,
            cacbohydrat: 16,
            protein: 26
        },
        infomations: 'Đậu phộng có khả năng tạo cảm giác no sau khi ăn, so với các món ăn nhẹ có lượng calo cao khác. Điều này cho phép người ăn tránh ăn quá nhiều calo. Do đó đậu phộng giúp bạn kiểm soát trọng lượng và ngăn tăng cân.',
    },
    {
        id: 13,
        name: 'Flax seeds',
        vnname: 'Hạt lanh',
        type: 'nutsandseeds',
        image: require('../assets/images/foods/flax.png'),
        color: '#d4cac3',
        nutritionalValue: {
            calories: 533,
            lipid: 42,
            cholesterol: 0,
            natri: 30,
            kali: 813,
            cacbohydrat: 29,
            protein: 18
        },
        infomations: 'Hàm lượng dinh dưỡng trong hạt lanh nâu và vàng đều như nhau. Trong khoảng 7g hạt lanh có chứa một lượng protein, chất xơ và axit béo omega-3 dồi dào. Bên cạnh đó, hạt lanh cũng chứa rất nhiều vitamin và khoáng chất khác nhau.',
    },
    {
        id: 14,
        name: 'Cashew nut',
        vnname: 'Hạt điều',
        type: 'nutsandseeds',
        image: require('../assets/images/foods/cashew.png'),
        color: '#e3ded3',
        nutritionalValue: {
            calories: 553,
            lipid: 44,
            cholesterol: 0,
            natri: 12,
            kali: 660,
            cacbohydrat: 30,
            protein: 18
        },
        infomations: 'Nhân điều mặc dù nếu so ra thì không chứa nhiều chất béo bằng các loại hạt khác, nhưng nó lại có chứa chất chống oxy hóa hàng đầu là axit béo omega-3, omega-6 và nhiều chất dinh dưỡng khác. Trong nhân điều rất giàu khoáng chất đồng, một thành phần thiết yếu của nhiều enzyme.',
    },
    {
        id: 15,
        name: 'Coconut',
        vnname: 'Dừa',
        type: 'nutsandseeds',
        image: require('../assets/images/foods/coconut.png'),
        color: '#c9b6a3',
        nutritionalValue: {
            calories: 354,
            lipid: 33,
            cholesterol: 0,
            natri: 20,
            kali: 356,
            cacbohydrat: 15,
            protein: 3.3
        },
        infomations: 'Nước dừa ít calo và chất béo nhưng lại rất giàu vitamin, khoáng chất và các chất dinh dưỡng khác như axit lauric, clorua, sắt, kali, magiê, canxi, natri và phốt pho. Trong mỗi 100ml nước dừa có chứa xấp xỉ 294mg kali, 118mg clorua nhưng chỉ có 25mg muối và 5mg dường.',
    },
]