export default active = [
    {
        id: 1,
        name: 'Food Choices',
        navigation: 'Food',
        icon: 'apple-alt',
        color: '#17b2ac',
        colorLight: '#b7f2f0',
        imageBackground: 'https://firebasestorage.googleapis.com/v0/b/ez-health.appspot.com/o/default%2Fapp_backgrounds%2Ffoods.png?alt=media&token=48000188-467b-4183-8216-5b9181169520',
    },
    {
        id: 2,
        name: 'Chilling Travel',
        navigation: '',
        icon: 'briefcase-medical',
        color: '#ed3c56',
        colorLight: '#f7ccd5',
        imageBackground: 'https://firebasestorage.googleapis.com/v0/b/ez-health.appspot.com/o/default%2Fapp_backgrounds%2Fbeach.png?alt=media&token=6cfc8efb-cfb2-4e01-86de-323c87e2a455',
    },
    {
        id: 3,
        name: 'Fitness',
        navigation: 'FitnessStack',
        icon: 'fist-raised',
        color: '#5495e5',
        colorLight: '#cdd8f7',
        imageBackground: 'https://firebasestorage.googleapis.com/v0/b/ez-health.appspot.com/o/default%2Fapp_backgrounds%2Ffitness.png?alt=media&token=f893afad-bc03-490e-a783-cf999a6f4fc9',
    },
    {
        id: 4,
        name: 'Relax Time',
        navigation: '',
        icon: 'weight-hanging',
        color: '#f9bb56',
        colorLight: '#f7e4d5',
        imageBackground: 'https://firebasestorage.googleapis.com/v0/b/ez-health.appspot.com/o/default%2Fapp_backgrounds%2Fsun.png?alt=media&token=c19bb89e-de5e-4b17-8182-a768dd286d75',
    },
    {
        id: 5,
        name: 'Meditation',
        navigation: '',
        icon: 'clock',
        color: '#A3A1F7',
        colorLight: '#D2D1FF',
        imageBackground: 'https://firebasestorage.googleapis.com/v0/b/ez-health.appspot.com/o/default%2Fapp_backgrounds%2Fmeditation.png?alt=media&token=8ed19780-e439-4eb9-92c9-61f3d83c1946',
    },
    {
        id: 6,
        name: 'Sleepy Sounds',
        navigation: 'SleepySounds',
        icon: 'music',
        color: '#2B2E35',
        colorLight: '#353840',
        imageBackground: 'https://firebasestorage.googleapis.com/v0/b/ez-health.appspot.com/o/default%2Fapp_backgrounds%2Fsleepy.png?alt=media&token=9a5a62e8-c0ef-4518-9ada-4feddbf2fd11',
    },
];
