
export default sleepy = [
    {
        id: 1,
        name: 'Quiet Cave',
        type: 'nature',
        blur: require('../assets/images/sleepy/blur/quietcave_blur.png'),
        image: require('../assets/images/sleepy/normal/quietcave.png'),
        sound: require('../assets/sounds/quietcave.mp3'),
    },
    {
        id: 2,
        name: 'Peaceful Night',
        type: 'nature',
        blur: require('../assets/images/sleepy/blur/peacefulnight_blur.png'),
        image: require('../assets/images/sleepy/normal/peacefulnight.png'),
        sound: require('../assets/sounds/peacefulnight.mp3'),
    },
    {
        id: 3,
        name: 'Desert',
        type: 'nature',
        blur: require('../assets/images/sleepy/blur/desert_blur.png'),
        image: require('../assets/images/sleepy/normal/desert.png'),
        sound: require('../assets/sounds/desert.mp3'),
    },
    {
        id: 4,
        name: 'Ocean',
        type: 'nature',
        blur: require('../assets/images/sleepy/blur/ocean_blur.png'),
        image: require('../assets/images/sleepy/normal/ocean.png'),
        sound: require('../assets/sounds/ocean.mp3'),
    },
    {
        id: 5,
        name: 'Winter',
        type: 'nature',
        blur: require('../assets/images/sleepy/blur/winter_blur.png'),
        image: require('../assets/images/sleepy/normal/winter.png'),
        sound: require('../assets/sounds/winter.mp3'),
    },
    {
        id: 6,
        name: 'Thunderstorm',
        type: 'nature',
        blur: require('../assets/images/sleepy/blur/thunderstorm_blur.png'),
        image: require('../assets/images/sleepy/normal/thunderstorm.png'),
        sound: require('../assets/sounds/thunderstorm.mp3'),
    },
    {
        id: 7,
        name: 'Autumn Woods',
        type: 'nature',
        blur: require('../assets/images/sleepy/blur/autumnwoods_blur.png'),
        image: require('../assets/images/sleepy/normal/autumnwoods.png'),
        sound: require('../assets/sounds/autumnwoods.mp3'),
    },
    {
        id: 8,
        name: 'Lake',
        type: 'nature',
        blur: require('../assets/images/sleepy/blur/lake_blur.png'),
        image: require('../assets/images/sleepy/normal/lake.png'),
        sound: require('../assets/sounds/lake.mp3'),
    },
    {
        id: 9,
        name: 'Bamboo Forest',
        type: 'nature',
        blur: require('../assets/images/sleepy/blur/bamboo_blur.png'),
        image: require('../assets/images/sleepy/normal/bamboo.png'),
        sound: require('../assets/sounds/bamboo.mp3'),
    },
    {
        id: 10,
        name: 'Rain on Window',
        type: 'rain',
        blur: require('../assets/images/sleepy/blur/rainonwindow_blur.png'),
        image: require('../assets/images/sleepy/normal/rainonwindow.png'),
        sound: require('../assets/sounds/rainonwindow.mp3'),
    },
    {
        id: 11,
        name: 'Rain in Forest',
        type: 'rain',
        blur: require('../assets/images/sleepy/blur/raininforest_blur.png'),
        image: require('../assets/images/sleepy/normal/raininforest.png'),
        sound: require('../assets/sounds/raininforest.mp3'),
    },
    {
        id: 12,
        name: 'Refeshing Rain',
        type: 'rain',
        blur: require('../assets/images/sleepy/blur/raininforest_blur.png'),
        image: require('../assets/images/sleepy/normal/refeshingrain.png'),
        sound: require('../assets/sounds/refreshingrain.mp3'),
    },
    {
        id: 13,
        name: 'Frogs',
        type: 'animals',
        blur: require('../assets/images/sleepy/blur/frogs_blur.png'),
        image: require('../assets/images/sleepy/normal/frogs.png'),
        sound: require('../assets/sounds/frogs.mp3'),
    },
    {
        id: 14,
        name: 'Crickets',
        type: 'animals',
        blur: require('../assets/images/sleepy/blur/crickets_blur.png'),
        image: require('../assets/images/sleepy/normal/crickets.png'),
        sound: require('../assets/sounds/crickets.mp3'),
    },
    {
        id: 15,
        name: 'Birds',
        type: 'animals',
        blur: require('../assets/images/sleepy/blur/birds_blur.png'),
        image: require('../assets/images/sleepy/normal/birds.png'),
        sound: require('../assets/sounds/birds.mp3'),
    },
    {
        id: 16,
        name: 'Owls',
        type: 'animals',
        blur: require('../assets/images/sleepy/blur/owls_blur.png'),
        image: require('../assets/images/sleepy/normal/owls.png'),
        sound: require('../assets/sounds/owls.mp3'),
    },

    {
        id: 17,
        name: 'Wolves',
        type: 'animals',
        blur: require('../assets/images/sleepy/blur/wolves_blur.png'),
        image: require('../assets/images/sleepy/normal/wolves.png'),
        sound: require('../assets/sounds/wolves.mp3'),
    },
    {
        id: 18,
        name: 'Waking Up',
        type: 'daytime',
        blur: require('../assets/images/sleepy/blur/wu_blur.png'),
        image: require('../assets/images/sleepy/normal/wu.png'),
        sound: require('../assets/sounds/wake_me_up.mp3'),
    },
    {
        id: 19,
        name: 'Nap',
        type: 'daytime',
        blur: require('../assets/images/sleepy/blur/nap_blur.png'),
        image: require('../assets/images/sleepy/normal/nap.png'),
        sound: require('../assets/sounds/nap.mp3'),
    },
    {
        id: 20,
        name: 'Lunch Break',
        type: 'daytime',
        blur: require('../assets/images/sleepy/blur/lb_blur.png'),
        image: require('../assets/images/sleepy/normal/lb.png'),
        sound: require('../assets/sounds/lb.mp3'),
    },
    {
        id: 21,
        name: 'Recharge',
        type: 'daytime',
        blur: require('../assets/images/sleepy/blur/rc_blur.png'),
        image: require('../assets/images/sleepy/normal/rc.png'),
        sound: require('../assets/sounds/rc.mp3'),
    },
    {
        id: 22,
        name: 'The Days',
        type: 'daytime',
        blur: require('../assets/images/sleepy/blur/dn_blur.png'),
        image: require('../assets/images/sleepy/normal/the_days.png'),
        sound: require('../assets/sounds/the_days.mp3'),
    },
    {
        id: 32,
        name: 'The Nights',
        type: 'nights',
        blur: require('../assets/images/sleepy/blur/dn_blur.png'),
        image: require('../assets/images/sleepy/normal/the_nights.png'),
        sound: require('../assets/sounds/the_nights.mp3'),
    },
]