export default active = [
    {
        id: 1,
        name: 'Food Choices',
        navigation: 'Food',
        icon: 'apple-alt',
        color: '#17b2ac',
        colorLight: '#b7f2f0',
        limitedFeature: false,
        imageBackground: require('../assets/backgrounds/apps/foods.png'),
    },
    {
        id: 2,
        name: 'Chilling Travel',
        navigation: '',
        icon: 'map-pin',
        color: '#ed3c56',
        colorLight: '#f7ccd5',
        limitedFeature: false,
        imageBackground: require('../assets/backgrounds/apps/beach.png'),
    },
    {
        id: 3,
        name: 'Fitness',
        navigation: 'FitnessStack',
        icon: 'fist-raised',
        color: '#5495e5',
        colorLight: '#cdd8f7',
        limitedFeature: false,
        imageBackground: require('../assets/backgrounds/apps/fitness.png'),
    },
    {
        id: 4,
        name: 'Relax Time',
        navigation: '',
        icon: 'clock',
        color: '#f9bb56',
        colorLight: '#f7e4d5',
        limitedFeature: false,
        imageBackground: require('../assets/backgrounds/apps/relax.png'),
    },
    {
        id: 5,
        name: 'Meditation',
        navigation: '',
        icon: 'circle',
        color: '#A3A1F7',
        colorLight: '#D2D1FF',
        limitedFeature: true,
        imageBackground: require('../assets/backgrounds/apps/meditation.png'),
    },
    {
        id: 6,
        name: 'Sleepy Sounds',
        navigation: 'SleepySounds',
        icon: 'music',
        color: '#2B2E35',
        colorLight: '#353840',
        limitedFeature: true,
        imageBackground: require('../assets/backgrounds/apps/sleepy.png'),
    },
];
